### ISSUE TITLE
Please tell me this will be based on mpv

### ISSUE THREAD

**Issue by Pentaphon** [pop-os/cosmic-player#14]
https://mpv.io/ would be great unless somebody is making their own rust-based back end somehow...

**Comment by M00NJ** [comment]
No, this uses FFmpeg and GStreamer. MPV is also mostly using FFmpeg.

**Comment by equeim** [comment]
And both are written in C which makes using Rust here kinda pointless since it's just a thin wrapper around underlying media framework (though I guess it fits better with Cosmic UI). And media formats parsing/decoding is the area where Rust's memory safety features would be most beneficial (ffmpeg and gstreamer both had their share of memory safety vulnerabilities and bugs).

Of course writing a multimedia framework from scratch supporting all popular formats is a huge task and likely beyond System76's resources right now, so it's understandable why they wouldn't do it.

**Comment by zefr0x** [comment]
Gstreamer has some plugins written in rust.

Any way, for any progress to be done for this, the best chance is contributing to existing libraries like [rav1e](https://github.com/xiph/rav1e), or porting any other media encoder/decoder into Rust one by one tell they are all adopted in Gstreamer.

**Comment by jackpot51** [comment]
We don't have plans to use anything other than gstreamer at this time.
